
WITH SESSIONS AS (SELECT * FROM {{ ref('int_product__events')}}),
SELECT SESSION_ID,
       USER_ID,
       ORDER_ID,
       SESSION_START,
       SESSION_END,
       ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY SESSION_START ASC)  AS SESSION_SEQ_ASC,
       ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY SESSION_START DESC) AS SESSION_SEQ_DESC
FROM SESSIONS;